"""add_access_control_and_join_requests

Revision ID: 371b27fe8dfd
Revises: ae65f8a143da
Create Date: 2025-12-19 16:26:28.852264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371b27fe8dfd'
down_revision: Union[str, Sequence[str], None] = 'ae65f8a143da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create club_requests table (for organizer club creation requests)
    op.create_table('club_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sports', sa.Text(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('groups_count', sa.Integer(), nullable=True),
    sa.Column('telegram_group_link', sa.String(length=500), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False, server_default='1'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='clubrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_requests_user_id'), 'club_requests', ['user_id'], unique=False)

    # Create join_requests table (for user join requests)
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='joinrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_activity_id'), 'join_requests', ['activity_id'], unique=False)
    op.create_index(op.f('ix_join_requests_club_id'), 'join_requests', ['club_id'], unique=False)
    op.create_index(op.f('ix_join_requests_group_id'), 'join_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_join_requests_status'), 'join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)

    # Add is_open columns with default value True for existing records
    op.add_column('activities', sa.Column('is_open', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('clubs', sa.Column('is_open', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'is_open')
    op.drop_column('activities', 'is_open')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_status'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_group_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_club_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_activity_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_club_requests_user_id'), table_name='club_requests')
    op.drop_table('club_requests')
    # ### end Alembic commands ###
