"""add strava webhook tables

Revision ID: 4ee6fec1b520
Revises: c3d4e5f6a7b8
Create Date: 2026-02-07 12:07:35.162089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4ee6fec1b520'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('strava_athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_webhook_events_strava_activity_id'), 'strava_webhook_events', ['strava_activity_id'], unique=True)
    op.create_index(op.f('ix_strava_webhook_events_strava_athlete_id'), 'strava_webhook_events', ['strava_athlete_id'], unique=False)
    op.create_table('pending_strava_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('strava_activity_data', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_strava_matches_user_id'), 'pending_strava_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_strava_matches_user_id'), table_name='pending_strava_matches')
    op.drop_table('pending_strava_matches')
    op.drop_index(op.f('ix_strava_webhook_events_strava_athlete_id'), table_name='strava_webhook_events')
    op.drop_index(op.f('ix_strava_webhook_events_strava_activity_id'), table_name='strava_webhook_events')
    op.drop_table('strava_webhook_events')
    # ### end Alembic commands ###
