"""add_user_onboarding_fields

Revision ID: ae65f8a143da
Revises: 42d9bd8b329d
Create Date: 2025-12-13 13:41:33.839526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae65f8a143da'
down_revision: Union[str, Sequence[str], None] = '42d9bd8b329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default for SQLite compatibility
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('preferred_sports', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_sports')
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###
