"""initial_schema

Revision ID: e15b3fe73ad0
Revises: 
Create Date: 2025-12-24 20:12:25.042339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15b3fe73ad0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('strava_link', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('show_photo', sa.Boolean(), nullable=False),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('preferred_sports', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('club_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sports', sa.Text(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('groups_count', sa.Integer(), nullable=True),
    sa.Column('telegram_group_link', sa.String(length=500), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='clubrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_requests_user_id'), 'club_requests', ['user_id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('invite_link', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('price_per_activity', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('bot_is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_member_count', sa.Integer(), nullable=True),
    sa.Column('sync_completed', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_city'), 'clubs', ['city'], unique=False)
    op.create_index(op.f('ix_clubs_is_demo'), 'clubs', ['is_demo'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('invite_link', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_city'), 'groups', ['city'], unique=False)
    op.create_index(op.f('ix_groups_club_id'), 'groups', ['club_id'], unique=False)
    op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_groups_is_demo'), 'groups', ['is_demo'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ORGANIZER', 'TRAINER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'LEFT', 'KICKED', 'BANNED', 'ARCHIVED', name='membershipstatus'), nullable=False),
    sa.Column('source', sa.Enum('ADMIN_IMPORT', 'CHAT_MEMBER_EVENT', 'MESSAGE_ACTIVITY', 'MANUAL_REGISTRATION', 'DEEP_LINK', name='membershipsource'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_club_id'), 'memberships', ['club_id'], unique=False)
    op.create_index(op.f('ix_memberships_group_id'), 'memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('recurring_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('total_occurrences', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('sport_type', sa.Enum('RUNNING', 'TRAIL', 'HIKING', 'CYCLING', 'YOGA', 'WORKOUT', 'OTHER', name='sporttype'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_templates_club_id'), 'recurring_templates', ['club_id'], unique=False)
    op.create_index(op.f('ix_recurring_templates_group_id'), 'recurring_templates', ['group_id'], unique=False)
    op.create_index(op.f('ix_recurring_templates_is_demo'), 'recurring_templates', ['is_demo'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('recurring_template_id', sa.String(length=36), nullable=True),
    sa.Column('recurring_sequence', sa.Integer(), nullable=True),
    sa.Column('sport_type', sa.Enum('RUNNING', 'TRAIL', 'HIKING', 'CYCLING', 'YOGA', 'WORKOUT', 'OTHER', name='sporttype'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE_GROUP', 'PRIVATE_CLUB', 'INVITE_ONLY', 'TELEGRAM_GROUP', 'PUBLIC', name='activityvisibility'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('gpx_file_id', sa.String(length=255), nullable=True),
    sa.Column('gpx_filename', sa.String(length=255), nullable=True),
    sa.Column('gpx_file_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'COMPLETED', 'CANCELLED', name='activitystatus'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_city'), 'activities', ['city'], unique=False)
    op.create_index(op.f('ix_activities_club_id'), 'activities', ['club_id'], unique=False)
    op.create_index(op.f('ix_activities_creator_id'), 'activities', ['creator_id'], unique=False)
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.create_index(op.f('ix_activities_group_id'), 'activities', ['group_id'], unique=False)
    op.create_index(op.f('ix_activities_is_demo'), 'activities', ['is_demo'], unique=False)
    op.create_index(op.f('ix_activities_sport_type'), 'activities', ['sport_type'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('ix_activities_visibility'), 'activities', ['visibility'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('activity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='joinrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_activity_id'), 'join_requests', ['activity_id'], unique=False)
    op.create_index(op.f('ix_join_requests_club_id'), 'join_requests', ['club_id'], unique=False)
    op.create_index(op.f('ix_join_requests_group_id'), 'join_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_join_requests_status'), 'join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    op.create_table('participations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'CONFIRMED', 'AWAITING', 'ATTENDED', 'MISSED', 'COMPLETED', 'CANCELLED', name='participationstatus'), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'NOT_REQUIRED', name='paymentstatus'), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participations_activity_id'), 'participations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_participations_user_id'), 'participations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participations_user_id'), table_name='participations')
    op.drop_index(op.f('ix_participations_activity_id'), table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_status'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_group_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_club_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_activity_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_activities_visibility'), table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_sport_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_demo'), table_name='activities')
    op.drop_index(op.f('ix_activities_group_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_index(op.f('ix_activities_creator_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_club_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_city'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_recurring_templates_is_demo'), table_name='recurring_templates')
    op.drop_index(op.f('ix_recurring_templates_group_id'), table_name='recurring_templates')
    op.drop_index(op.f('ix_recurring_templates_club_id'), table_name='recurring_templates')
    op.drop_table('recurring_templates')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_group_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_club_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_groups_is_demo'), table_name='groups')
    op.drop_index(op.f('ix_groups_creator_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_club_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_city'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_clubs_is_demo'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_city'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_club_requests_user_id'), table_name='club_requests')
    op.drop_table('club_requests')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
